language: node_js
cache:
  directories:
    - ~/.npm
notifications:
  email: true
node_js:
  - '10'
before_install:
  - npm install -g npm@5
install: npm install
jobs:
  include:
    - stage: test
      script:
        - npm run lint
        - npm run test
        - npm run build
    - stage: deploy
      if: branch = master
      before_script: npm run build
      script: npm run travis-deploy-once "npm run semantic-release"
